### ISSUE TITLE
App FC when Wi-Fi is off and displaying "Known hotspots"

### ISSUE THREAD

**Issue by LaGlobule** [BramBonne/privacypolice#11] opened 2015-05-21 11:23 UTC
Hi Bram,
I've got an issue on current version of the app.
Here is the scenario :
- I switch off my Wi-Fi on the phone,
- I launch the app --> the main screen appears,
- I select "Known hotspots" --> it takes a long time to display a black screen and then FC.

Can you please check and let me know ?
Thanks again for this very useful app.
La Globule

**Comment by BramBonne** [comment] 2015-05-21 12:04
Hi!

Thanks for creating this bug report! As I'm not able to reproduce this crash on my own device (I rebooted with Wi-Fi disabled, but the screen displays just fine), could you either:

* Send a logcat of the moment the bug appears? (you can find out how to do that [here](https://www.youtube.com/watch?v=wv1x24CZrvY) and [here](http://wiki.cyanogenmod.org/w/Doc:_debugging_with_logcat))
* Provide a bit more info? (which device are you using? Are there already networks in your Known Hotspots list?)
* Send in a crash report through Google Play?

Thanks in advance!

Bram

**Comment by BramBonne** [comment] 2015-10-12 14:11
Closing this issue for lack of info / lack of reproducibility. Anyone, feel free to reopen this issue if you encounter this issue.

**Closed by BramBonne** 2015-10-12 14:11 UTC
Labels: bug, help wanted
