### ISSUE TITLE
the app is not working property on cm13

### ISSUE THREAD

**Issue by caioau** [BramBonne/privacypolice#42] opened 2016-07-10 17:09 UTC
Hi I loved the app, 

but it is not working property on cyanogenmod 13.

When I connect to a wifi station, it works fine for 2 minutes e suddenly disconnects and never reconnects again.

any sugestions?

Thanks

**Comment by ka223** [comment] 2016-08-05 06:39
On my cm13 device, when data privacy is activated, wifi connects and immediately disconnects with wifi-connectionerror. :(

**Comment by jomo** [comment] 2016-08-05 12:11
There's some information about complications in #30, perhaps it helps you?

**Comment by ka223** [comment] 2016-08-07 14:48
I need to grant location access?
The GPS is every time on, if I allow switching to wifi location, google play services can collect location data. This is not a good option right now.

**Comment by BramBonne** [comment] 2016-10-03 13:40
Unfortunately, as per #30 , this is the only viable option in Android M and up. I do appreciate your concern.

I'll mark this bug as a duplicate of #30.

**Closed by BramBonne** 2016-10-03 13:40 UTC
