### ISSUE TITLE
Android does not reconnect back to well-known Wi-Fi networks

### ISSUE THREAD

**Issue by raulsiles** [BramBonne/privacypolice#22] opened 2015-10-07 19:08 UTC
I'm using Wi-Fi Privacy Police version 2.0.1 in a test Nexus 5 mobile device running Android 5.1.1 (build LMY48M). This behavior was present also in previous Android 5.x versions and builds.

The mobile device is connected to a Wi-Fi network and it leaves that physical location. When it returns back after a few minutes, it does not reconnect back automatically to any of the well-known Wi-Fi networks. The location has a few well-known Wi-Fi networks (and access points) it can connect to, and all them have been previously registered in the list of "Known hotspots" (both SSID and BSSID).

Both options "Privacy protection" and "Data protection" are enabled in the app.

If the Wi-Fi interface is turned off and on again, the device automatically connects to one of the well-known Wi-Fi networks.

Unfortunately, I've not had the chance of capturing the Wi-Fi traffic in this scenario to know what it's really going on, but I've preferred to submit this issue and confirm if it is a well known misbehavior.

**Comment by raulsiles** [comment] 2015-10-07 19:17
After opening this issue I have seen there is a related but closed issue 19 (https://github.com/BramBonne/privacypolice/issues/19). I didn't mentioned it before, but I can confirm that uninstalling the app does solve the problem for me too (the issue does not appear without the app)... but I don't want to uninstall it ;-)

I'm going to try to disable both options "Privacy protection" and "Data protection" in the app (but leave the app installed), and check if I can still reproduce this issue.

I think it would be positive to leave this issue open till there is a solution that works in Android 5.1.x or greater, as I wouldn't like to admit the app will only support Android < 5.1 ;-)

**Comment by raulsiles** [comment] 2015-10-07 20:24
When the app is installed but both options are disabled, everything works as expected and the device connects back automatically to the well-known Wi-Fi networks. 

However, when the "Data protection" option is enabled, the problem reappears. Turning off that option does not solve the problem. It is required to turn off and on the Wi-Fi interface for the device to connect back automatically.

**Comment by BramBonne** [comment] 2015-10-12 14:08
Thanks for your feedback. I agree that this issue should remain open until a fix is available, so I'm closing this as a duplicate of #19 and will reopen that issue.

I'll look into it as soon as I can get my hands on a device that has Android 6.0 installed to see whether the issue persists there.

**Closed by BramBonne** 2015-10-12 14:08 UTC
