### ISSUE TITLE
Add indication whether a known hotspot is trusted or blocked

### ISSUE THREAD

**Issue by ThomasHabets** [BramBonne/privacypolice#39] opened 2016-04-18 18:36 UTC
"Known hotspots" only shows hotspots it knows about, or has seen. It doesn't show which ones are blocked and which are trusted though.

Suggested: green blob next to name of trusted MAC address, red next to blocked. And then some combination of the colours on the SSID level.

**Comment by BramBonne** [comment] 2016-04-26 11:29
Hi Thomas,

It does show which ones are blocked and trusted as soon as they are in range (exactly how you describe it: with either a green or a red icon). The visual is thus based on the current action taken by PrivacyPolice, as it might be that some other hotspots might be trusted.

I'm closing this because it works as intended. Feel free to re-open if you feel otherwise.

**Comment by ThomasHabets** [comment] 2016-04-26 13:09
I don't seem to have re-open access, and no I don't think my concern is addressed by what you said.

Example use cases:
* "Uh oh, did I press 'yes' on one of the 'AndroidAP' ones? Oh… it's not in range so I can't check."
* "Which MAC addresses have I said yes and no to. Can't see that"

**Comment by BramBonne** [comment] 2016-04-26 13:17
Allright thank you for your comment, that is a valid use case. I'll implement this if I find the time, shouldn't be too much work.

**Comment by BramBonne** [comment] 2016-04-30 11:35
Implemented in 4438e728a292f8d0d54e66566ab8db5d1c498666. Will be available with the next release.

**Closed by BramBonne** 2016-04-30 11:35 UTC

**Comment by ThomasHabets** [comment] 2016-05-01 14:45
Sweet! Thanks!
